feat: Add new icon
debionetwork/ui-icons pull request #1
Opened 2022-07-26 06:21 UTC by bukandicki

- Changelog
Add several new icons

2022-07-28 03:50 UTC, ciniiia approved these changes

2022-08-02 03:33 UTC, agustinustheo commented
Will add changes.

2022-08-02 03:36 UTC, agustinustheo requested changes
Will leave changes

2022-08-02 09:32 UTC, agustinustheo approved these changes

2022-08-02 09:32 UTC, merged